config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :inspections do
    collection do
      get '/realtors', action: 'realtors'
      get '/marketing', action: 'marketing'
    end
    resources :agreements, only: [:new, :create, :edit, :update]
  end
  resources :agreements, only: [:index, :show]

  resources :users do
    collection do
      post '/create_inspector', action: 'create_inspector'
    end
  end

  root to: "pages#index"
end

app/models/user.rb
class User < ApplicationRecord

  has_many :inspections

  after_create :assign_inspector_role

  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def assign_inspector_role
    self.add_role(:inspector) if self.roles.blank?
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, :only => [:destroy, :show]

  def show
  end

  def new
    @user = User.new
  end

  def create_inspector
   @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def index
    @users = User.all
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'Inspector was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(
      :first_name,
      :last_name,
      :email,
      :password,
      :password_confirmation
    )
  end

end

app/views/users/_form.html.erb
<div class='panel panel-default'>
  <div class='panel-heading'>
    <h3> New Inspector </h3>
  </div>

  <div class='panel-body'>
    <%= form_for @user, url: create_inspector_users_path, html: {class: 'form form-signup'} do |f| %>

      <div class="form-group">
        <%= f.label :email %><br />
        <%= f.email_field :email, autofocus: true, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, autocomplete: "off", class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation %><br />
        <%= f.password_field :password_confirmation, autocomplete: "off", class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.submit "Create", class: 'btn btn-primary btn-lg col-xs-12' %>
      </div>
    <% end %>
  </div>

</div>

app/views/users/index.html.erb
<div class='panel panel-default'>
  <div class='panel-heading'>
    <h3> Inspectors
    <%= link_to 'Create User', new_user_path, class: 'btn btn-primary pull-right' %>
    </h3>
  </div>

  <div class='panel-body'>
    <table class='table'>
      <tr>
        <th>Email</th>
        <th>Actions</th>
      </tr>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td> <%= user.email %> </td>
            <td><%= link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

</div>

app/views/users/new.html.erb
<%= render :partial => 'form' %>