config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :inspections do
    collection do
      get '/realtors', action: 'realtors'
      get '/marketing', action: 'marketing'
    end
    resources :agreements, only: [:new, :create, :edit, :update]
  end
  resources :agreements, only: [:index, :show]

  resources :users do
    collection do
      post '/create_inspector', action: 'create_inspector'
    end
  end

  root to: "pages#index"
end

app/models/inspection.rb
class Inspection < ApplicationRecord
  mount_uploader :report, ReportUploader
  serialize :email_option, Array

  has_many :agreements, dependent: :destroy
  belongs_to :user

  EMAIL_OPTIONS = ['buyer', 'realtor', 'none']

  def email_inspection
    self.email_option.each do |recipient|
      UserMailer.notify_inspection(self, recipient).deliver
    end
  end
end

app/controllers/inspections_controller.rb
class InspectionsController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :set_inspection, only: [:show, :edit, :update, :destroy]

  # GET /inspections
  # GET /inspections.json
  def index
    if params[:from].present?
      @inspections = collection.where('created_at > ? ', params[:from])
    else
      @inspections = collection
    end
  end

  # GET /inspections/1
  # GET /inspections/1.json
  def show
    redirect_to @inspection.report.url
  end

  # GET /inspections/new
  def new
    @inspection = Inspection.new
  end

  # GET /inspections/1/edit
  def edit
  end

  # POST /inspections
  # POST /inspections.json
  def create
    @inspection = current_user.inspections.new(inspection_params)

    respond_to do |format|
      if @inspection.save
        @inspection.email_inspection

        format.html { redirect_to inspections_path, notice: 'Inspection was successfully created.' }
        format.json { render :show, status: :created, location: @inspection }
      else
        format.html { render :new }
        format.json { render json: @inspection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inspections/1
  # PATCH/PUT /inspections/1.json
  def update
    respond_to do |format|
      if @inspection.update(inspection_params)
        format.html { redirect_to @inspection, notice: 'Inspection was successfully updated.' }
        format.json { render :show, status: :ok, location: @inspection }
      else
        format.html { render :edit }
        format.json { render json: @inspection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inspections/1
  # DELETE /inspections/1.json
  def destroy
    @inspection.destroy
    respond_to do |format|
      format.html { redirect_to inspections_url, notice: 'Inspection was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def realtors
    @realtors = {}
    collection.each do |i|
      next if i.realtors_name.nil?

      @realtors[i.realtors_name] ||= { count: 0, last_referal: nil }
      @realtors[i.realtors_name][:count] += 1
      @realtors[i.realtors_name][:last_referal] = (i.created_at.to_i > @realtors[i.realtors_name][:last_referal].to_i) ? i.created_at : @realtors[i.realtors_name][:last_referal]
    end
  end

  def marketing
    @monthly_inspections = {}
    @inspections = Inspection.where('created_at >= ?', Date.today.beginning_of_year).group_by { |i| i.created_at.to_date.beginning_of_month.to_s }

    months_of_year.each do |month|
      inspections_of_the_month = @inspections[month] || []
      @monthly_inspections[month] = {count: inspections_of_the_month.count, revenue: inspections_of_the_month.map(&:inspection_fee).sum}
    end
  end

  private

    def collection
      current_user.has_role?(:inspector) ? current_user.inspections : Inspection.all
    end

    def months_of_year
      (Date.today.beginning_of_year..Date.today.end_of_year).map(&:beginning_of_month).uniq.map(&:to_s)
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_inspection
      @inspection = Inspection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inspection_params
      params.require(:inspection).permit(
        :report_type,
        :inspection_type,
        :property_code,
        :address,
        :buyers_name,
        :buyers_phone,
        :buyers_email,
        :realtors_name,
        :realtors_phone,
        :realtors_email,
        :realtors_company,
        :report,
        :marketing_source,
        :paying_at_closing,
        :estimated_closing_date,
        :inspection_fee,
        email_option: []
      )
    end
end

app/helpers/inspections_helper.rb
module InspectionsHelper
end

app/views/inspections/_form.html.erb
<%= form_for(inspection, html: {class: 'form-horizontal col-md-12'}) do |f| %>
  <% if inspection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(inspection.errors.count, "error") %> prohibited this inspection from being saved:</h2>

      <ul>
      <% inspection.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class='form-group'>
    <label for="Report Type" class='control-label'>Report Type</label>
    <div>
      <label for="" class='radio-inline'>
        <%= f.radio_button :report_type, 'new' %>
        New Report
      </label>

      <label for="" class='radio-inline'>
        <%= f.radio_button :report_type, 'update' %>
        Update BR Report
      </label>

      <label for="" class='radio-inline'>
        <%= f.radio_button :report_type, 'oops' %>
        Oops
      </label>
    </div>
  </div>

  <div class='form-group'>
    <label for="Inspection Type">Inspection Type</label>
    <div>
      <label for="" class='radio-inline'>
        <%= f.radio_button :inspection_type, 'buyer' %>
        Buyers
      </label>

      <label for="" class='radio-inline'>
        <%= f.radio_button :inspection_type, 'seller' %>
        Sellers BR
      </label>

      <label for="" class='radio-inline'>
        <%= f.radio_button :inspection_type, 'testing' %>
        E-Testing
      </label>
    </div>
  </div>

  <div class='form-group'>
    <label for=" Property Code"> Property Code <small> (Oops only) </small></label>
    <%= f.text_field :property_code, class: 'form-control' %>
  </div>

  <div class='form-group'>
    <label for=" Address"> Address</label>
    <%= f.text_field :address, class: 'form-control' %>
  </div>

  <div class='form-group'>
    <label for="Inspection Report">Inspection Report</label>
    <%= f.file_field :report %>
  </div>

  <div class='form-group'>
    <label for=" Buyers Name"> Buyers Name</label>
    <%= f.text_field :buyers_name, class: 'form-control' %>
  </div>

  <div class='form-group'>
    <label for=" Buyers Phone"> Buyers Phone</label>
   <%= f.text_field :buyers_phone, class: 'form-control' %>
  </div>

  <div class='form-group'>
    <label for=" Buyers Email"> Buyers Email</label>
    <%= f.text_field :buyers_email, class: 'form-control' %>
  </div>

  <div class='form-group'>
    <label for="Realtors Name">Realtors Name</label>
    <%= f.text_field :realtors_name, class: 'form-control'  %>
  </div>

  <div class='form-group'>
    <label for=" Realtors Phone"> Realtors Phone</label>
    <%= f.text_field :realtors_phone, class: 'form-control' %>
  </div>

  <div class='form-group'>
    <label for=""> Realtors Email</label>
    <%= f.text_field :realtors_email, class: 'form-control' %>
  </div>

  <div class='form-group'>
    <label for=""> Realtors Company</label>
    <%= f.text_field :realtors_company, class: 'form-control' %>
  </div>

  <div class='form-group'>
    <label for=""> Marketing Source</label>
    <%= f.text_field :realtors_company, class: 'form-control' %>
  </div>

  <div class='form-group'>
    <label for=""> Paying at Closing</label>
    <div>
      <label for="">
        <%= f.radio_button :paying_at_closing, false %>
        No
      </label>
      <label for="">
        <%= f.radio_button :paying_at_closing, true %>
        Yes
      </label>
    </div>
  </div>

  <div class='form-group'>
    <label for=""> Estimated Closing Date</label>
    <%= f.date_field :estimated_closing_date, class: 'form-control' %>
  </div>

  <div class='form-group'>
    <label for=""> Inspection Fee</label>
    <%= f.text_field :inspection_fee, class: 'form-control' %>
  </div>

  <div class='form-group'>
    <label for=""> Email Options</label>
    <div>
      <% Inspection::EMAIL_OPTIONS.each do |opt|  %>
        <label for="" class='checkbox-inline'>
          <%= f.check_box :email_option, {multiple: true}, opt, nil %>
          <% if opt == 'none' %>
            None
          <% else %>
            Email Report to <%= opt %>
          <% end %>
        </label>
      <% end %>
    </div>
  </div>


  <div class="form-group">
    <%= f.submit nil, class: 'btn btn-primary col-xs-12' %>
  </div>
<% end %>

app/views/inspections/edit.html.erb
<h1>Editing Inspection</h1>

<%= render 'form', inspection: @inspection %>

<%= link_to 'Show', @inspection %> |
<%= link_to 'Back', inspections_path %>

app/views/inspections/index.html.erb
<div class='panel panel-default'>
  <div class='panel-heading'>
    <h1>Inspections</h1>
    <%= form_tag inspections_path, method: :get do %>
      <label for="From ">From </label>
      <%= date_field_tag :from %>
      <%= submit_tag 'Search' %>
    <% end %>
  </div>

  <div class='panel-body'>

    <table class='table'>
      <thead>
        <tr>
          <th>Address</th>
          <th>Upload Date</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @inspections.each do |inspection| %>
          <tr>
            <td> <%= inspection.address %> </td>
            <td> <%= inspection.created_at.to_formatted_s(:short) %> </td>
            <td><%= link_to 'Show', inspection %></td>
            <td><%= link_to 'Edit', edit_inspection_path(inspection) %></td>
            <td><%= link_to 'Destroy', inspection, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Inspection', new_inspection_path, class: 'btn btn-primary' %>

  </div>

</div>

app/views/inspections/marketing.html.erb
<div class='panel panel-default'>
  <div class='panel-heading'>
    <h2>Marketing</h2>
  </div>

  <div class='panel-body'>
    <h4>Revenue</h4>
    <%= column_chart @monthly_inspections.map{ |key, val| [Date.parse(key).strftime('%b'), val[:revenue]] }, adapter: "google", library: {vAxis: {format: 'currency'}} %>
  </div>

  <div class='panel-body'>
    <h4>Inspections</h4>
    <%= column_chart @monthly_inspections.map{ |key, val| [Date.parse(key).strftime('%b'), val[:count]] }, adapter: 'google' %>
  </div>

</div>

app/views/inspections/new.html.erb
<div class='panel panel-default'>
  <div class='panel-heading'>
    <h2>New Inspection</h2>
  </div>

  <div class='panel-body'>
    <%= render 'form', inspection: @inspection %>
    <%= link_to 'Back', inspections_path %>
  </div>

</div>

app/views/inspections/realtors.html.erb
<div class='panel panel-default'>
  <div class='panel-heading'>
    <h3>Realtor Activity</h3>
  </div>

  <div class='panel-body'>
    <table class='table'>
      <thead>
        <tr>
          <th>Realtor</th>
          <th>Total Referrals</th>
          <th>Last Referral</th>
        </tr>
      </thead>

      <tbody>
        <% @realtors.each do |key, val| %>
          <tr>
            <td> <%= key %> </td>
            <td><%= val[:count] %></td>
            <td><%= val[:last_referal].to_formatted_s(:short) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

  </div>

</div>

app/views/inspections/show.html.erb
<%= link_to 'Edit', edit_inspection_path(@inspection) %> |
<%= link_to 'Back', inspections_path %>