config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :inspections do
    collection do
      get '/realtors', action: 'realtors'
      get '/marketing', action: 'marketing'
    end
    resources :agreements, only: [:new, :create, :edit, :update]
  end
  resources :agreements, only: [:index, :show]

  resources :users do
    collection do
      post '/create_inspector', action: 'create_inspector'
    end
  end

  root to: "pages#index"
end

app/views/layouts/_header.html.erb
<nav class='navbar navbar-default'>
   <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#sidebar-nav" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>


      <p class='navbar-btn visible-xs'>
        <%= link_to('New Report', new_inspection_path, class: 'btn btn-success btn-left-margin') %>
        <%= link_to('View Reports', inspections_path, class: 'btn btn-primary') %>
      </p>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbar-header">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <p class='navbar-btn'>
            <%= link_to('New Report', new_inspection_path, class: 'btn btn-success') %>
          </p>
        </li>
        <li>
          <p class='navbar-btn '>
            <%= link_to('View Reports', inspections_path, class: 'btn btn-primary btn-left-margin') %>
          </p>
        </li>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_sidebar.html.erb
<div class='col-md-12 no-padding' >
  <br />
  <h3 class="text-center brand" href="#">BoostInspect</h3>

  <ul class='nav nav-pills nav-stacked' >
    <li>
      <%= link_to root_path do %>
        <i class='fa fa-home'></i>
        Home
      <% end %>
    </li>

    <li>
      <%= link_to inspections_path do %>
        <i class='fa fa-file-text'></i>
        Reports & Clients
      <% end %>
    </li>

    <li>
      <%= link_to marketing_inspections_path do %>
        <i class='fa fa-bar-chart'></i>
        Marketing
      <% end %>
    </li>
    <li>
      <%= link_to '#' do %>
        <i class='fa fa-cogs'></i>
        Supplies
      <% end %>
    </li>
    <li>
      <%= link_to agreements_path do %>
        <i class='fa fa-cogs'></i>
        E-Signed Agreements
      <% end %>
    </li>
    <li>
      <%= link_to realtors_inspections_path do %>
        <i class='fa fa-cogs'></i>
        Realtor Activity
      <% end %>
    </li>
    <% if !current_user.has_role?(:inspector) %>
      <li>
        <%= link_to users_path do %>
          <i class='fa fa-user'></i>
          Inspectors
        <% end  %>
      </li>
    <% end %>

  </ul>

  <ul class='nav nav-pills nav-stacked' >
    <li>
      <%= link_to destroy_user_session_path, method: :delete do %>
      <i class='fa fa-power-off'></i>
      Logout
    <% end %>
    </li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Homeinspector</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css" media="screen" title="no title" charset="utf-8">

  </head>

  <body class='skin-light'>
    <div class='container-fluid no-padding'>
      <div class='col-xs-9 col-sm-9 col-md-3 sidebar-left nav-collapse collapse' id='sidebar-nav'>
        <%= render partial: 'layouts/sidebar' %>
      </div>
      <div class='col-xs-12 col-sm-12 col-md-9 col-md-offset-3 no-padding'>
        <%= render 'layouts/header' %>
      </div>
      <div class='col-xs-12 col-sm-12 col-md-9 col-md-offset-3 content'>

        <% if notice %>
          <p class="alert alert-info"><%= notice %></p>
        <% end %>

        <%= yield %>
      </div> 
    </div>


  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Homeinspector</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'devise', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class='splash app'>
    <div class='container'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/guest.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Homeinspector</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css" media="screen" title="no title" charset="utf-8">

  </head>

  <body class='skin-light'>
    <div class='container'>
      <div class='col-xs-12 col-sm-12 col-md-12 text-center'>

        <% if notice %>
          <p class="alert alert-info"><%= notice %></p>
        <% end %>

        <%= yield %>
      </div> 
    </div>


  </body>
</html>